version: '3.1'

services:
  mysql:
    image: mysql
    container_name: mysqlldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: "srpack"
      MYSQL_PASSWORD: "srpack"
    volumes:
    - ./sql-data/db:/var/lib/mysql
    ports:
      - 3306:3306